name: recipe
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

dependencies:
  build_runner: ^2.6.0
  crypto: ^3.0.6
  dart_jsonwebtoken: ^3.2.0
  freezed: ^3.0.0-0.0.dev
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.10.0
  mailer: ^6.5.0
  postgres: ^3.5.6
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  uuid: ^4.5.1

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
